[package]
name = "sharust"
version = "0.1.0"
authors = ["Paul <paul@niobium.me>"]

[dependencies]
serde = "0.9.14"
hyper = "0.10.8"
multipart = "0.12.0"
notify-rust = "3.3.0"
serde_json = "0.9.10"
serde_derive = "0.9.14"
hyper-native-tls = "0.2.2"
clap = { version = "2.23.2", features = ["yaml"] }